### PR TITLE
Enable deserializing IRedisCacheItem and IRedisCacheItem<T>

### LINKED ISSUE #13: Error when deserializing with Json.Net
Repro:

Reference [TagCache.Redis.Json.Net](https://www.nuget.org/packages/TagCache.Redis.Json.Net/)

	void Main()
	{
		var redisConnMgr = new TagCache.Redis.RedisConnectionManager("localhost");
		var config = new TagCache.Redis.CacheConfiguration(redisConnMgr)
		{
			Serializer = new TagCache.Redis.Json.Net.JsonSerializationProvider(),
		};
		var cacheProvider = new TagCache.Redis.RedisCacheProvider(config);
		
		cacheProvider.Set("foo", new Foo(), DateTime.UtcNow + TimeSpan.FromMinutes(5));
		/*
		{
			"Value": {
				"Bar": "baz"
			},
			"Key": "foo",
			"Tags": null,
			"Expires": "2016-01-13T15:10:21.837778Z"
		}
		*/
		
		cacheProvider.Get<Foo>("foo");
		// ERROR:
		// Could not create an instance of type 
		// TagCache.Redis.Interfaces.IRedisCacheItem`1[Foo].
		// Type is an interface or abstract class and cannot be instantiated.
	}
	
	public class Foo
	{
		public string Bar = "baz";
	}

*Expected outcome*: json at redis key "foo" successfully deserialized into type `Foo`.

*Actual outcome*: json.net error: 
<q>Could not create an instance of type TagCache.Redis.Interfaces.IRedisCacheItem`1[Foo]. Type is an interface or abstract class and cannot be instantiated. Path 'Value', line 1, position 9.</q>

### PR DESCRIPTION
**Pull request by CrescentFresh**
Fixes #13

### CODE REVIEW

**Comment by jmenziessmith** [comment]
Thanks. I've added a test to cover this. If you know how to handle this for MessagePack, would you be kind enough to do the same? I'm not sure if its possible from the docs as the custom serializers dont seem to get applied with abstract types.

**Comment by CrescentFresh** [comment]
At the moment I don't have time I'm sorry.

**Comment by CrescentFresh** [comment]
When can you push to nuget?

**Comment by jmenziessmith** [comment]
Next version should go out tonight.

**Pull request merged**
